### PR TITLE
Add new feat to format number functions

### PR DESCRIPTION
**Pull request by pkretzschmar**
Now the format functions will return <0.0001 if the formatted number is smaller than that.﻿

### CODE REVIEW

**Comment by MohammadPCh** [comment]
@pkretzschmar Please connect the issue in the description. Thanks

**Comment by aminlatifi** [comment]
> @pkretzschmar Please connect the issue in the description. Thanks

https://github.com/giveth/giveconomy/issues/392

**Comment by MohammadPCh** [comment]
I think we should change all numbers. my suggestion is to change TOKEN_PRECISION to 4 and use it in the code (even hardcoded numbers)
@pkretzschmar

**Review by MohammadPCh — CHANGES_REQUESTED** [review]
Please use TOKEN_PRECISION in the code, and change it to 4. also, you can implement it dynamically. lmk if you need help.

**Review by MohammadPCh — APPROVED** [review]
Thank you @pkretzschmar,
I fixed the formatWeiHelper function too.

**Pull request merged**
