### PR TITLE
Fix Givbacks round date

### PR DESCRIPTION
**Pull request by marthendalnunes**
Fixes:
- https://github.com/Giveth/GIVeconomy/issues/247

### CODE REVIEW

**Comment by MohammadPCh** [comment]
@marthendalnunes is it ready for review?

**Comment by marthendalnunes** [comment]
@MohammadPCh yes

**Review by MohammadPCh — CHANGES_REQUESTED** [review]
@marthendalnunes, you shouldn't call setDate on token distro,
also, please check the start and end time with @laurenluz, because i think we should calculate it in a different way.

**Comment by MohammadPCh** [comment]
@marthendalnunes 
I have fixed and merge it.

**Review by MohammadPCh — APPROVED** [review]

**Pull request merged**
