### PR TITLE
Add Reward menu

### PR DESCRIPTION
**Pull request by MohammadPCh**
fix Giveth/GIVeconomy#417

### CODE REVIEW

**Comment by aminlatifi** [comment]
Nice!
Seems good to me
Just one point! The `GIVFarm and Givgarden` section is zero until user opens the farm tab!

image

**Comment by aminlatifi** [comment]
> Nice! Seems good to me Just one point! The `GIVFarm and Givgarden` section is zero until user opens the farm tab!
> 
> image

I know it need big refactoring, we should discuss it.

**Comment by MohammadPCh** [comment]
> > Nice! Seems good to me Just one point! The `GIVFarm and Givgarden` section is zero until user opens the farm tab!
> > image
> 
> I know it need big refactoring, we should discuss it.

@aminlatifi 
I think it's better to think about this issue when we are refactoring requests and providers.

**Comment by aminlatifi** [comment]
OK,

**Pull request merged**
